- speakeasy/common.py
`self.handle` is present for the other hook types but missing for `ReadMemHook`
> ReadMemHook: save native handle

- speakeasy/winenv/api/usermode/msvcrt.py
First commit on this project, starting with an easy one.  
This is support for `msvcrt.strlen`. 
I tested it on sample `a8068055457daa6a9b15f469e39f9138` with the following log below.
```
0x401014: 'MSVCRT.memset(0x41d84c, 0x0, 0x24)' -> 0x41d84c
0x401021: 'KERNEL32.GetModuleHandleA(0x0)' -> 0x400000
0x40103a: 'KERNEL32.HeapCreate(0x0, 0x1000, 0x0)' -> 0x40b0
0x409be2: 'KERNEL32.HeapCreate(0x0, 0x1000, 0x0)' -> 0x40d0
0x409c10: 'KERNEL32.HeapAlloc(0x40d0, 0x0, 0x10)' -> 0x40f0
0x409324: 'MSVCRT.memset(0x41d89c, 0x0, 0x30)' -> 0x41d89c
0x409cea: 'MSVCRT.strlen(0x40c033)' -> 0x6
0x409d0d: 'KERNEL32.HeapAlloc(0x40d0, 0x0, 0xb)' -> 0x4110
0x409c93: 'MSVCRT.strlen(0x4110)' -> 0x6
0x409caf: 'KERNEL32.HeapAlloc(0x40d0, 0x0, 0xb)' -> 0x4120
0x409cea: 'MSVCRT.strlen(0x40c02b)' -> 0x7
0x409d0d: …
```
> Support for msvcrt.strlen

- speakeasy/winenv/api/usermode/msvcrt.py
Another simple PR to get coverage on `wcslen`.  I largely borrowed from the implementation of strlen that is right above it.
I also noticed that there are 2 implementations of `strlen`, I put in a PR for one (which can probably be deleted now) and the other one looks like it got added tonight.
> Adding support for msvcrt.wcslen

- speakeasy/winenv/api/usermode/msvcrt.py
Adding support for strncpy.  
I did have a question on this commit.  
According to the MSDN documentation on strncpy: `If count is greater than the length of strSource, the destination string is padded with null characters up to length count. `
So I have accounted for this in 
```
s += '\x00'*(size-len(s))
```
The method that writes the string to memory is `self.write_string(s, dest)`.  Is `write_string` going to truncate the string at the null or write the entire string?
Thanks for the help.
> Adding support for msvcrt.strncpy

- speakeasy/winenv/api/usermode/user32.py
For this I largely borrowed from qiling's implementation.  I changed the keyboard to default to  `IBM enhanced (101- or 102-key) keyboard` rather than ` Japanese keyboard `
https://github.com/qilingframework/qiling/blob/078996ce2dbe61c3da0b9b352634876d0e38be0f/qiling/os/windows/dlls/user32.py#L559
> Adding support for user32.GetKeyboardType

- speakeasy/winenv/api/usermode/msvcrt.py
This adds support for strcat in msvcrt.  This mostly copies another implementation of strcat, but there doesn't need to be a width check.
I also removed the first `strlen` from msvcrt as there are 2 implementations and the one you added is better.
> Adding support for msvcrt.strcat

- speakeasy/winenv/api/usermode/msvcrt.py
Basically just `memcpy`.  This can be tested with sample `eaec3e5334b937a526a418b88d63291c`
> Adding support for msvcrt.memmove

- speakeasy/winenv/api/usermode/msvcrt.py
More string functions.  
Also, I noticed in the function above (`strcpy`) that it returns `len(s)` and not `dest`?  I didn't add in a PR to fix that, I just didn't know if it was by design.
> Added support for msvcrt.wcscpy

- speakeasy/windows/winemu.py
This change redirects winsocks 1.0 API calls from winsock and wsock32 dlls to ws2_32.dll (2.0 API).
Let me know if this isn't the planned way to deal with this.
> redirect winsock and wsock32 to ws2_32.dll

- speakeasy/winenv/api/usermode/kernel32.py
This is a simple PR adding in support for GetThreadLocale 
The constant returned is for LOCALE_CUSTOM_DEFAULT `0xC000` 
https://docs.microsoft.com/en-us/windows/win32/intl/locale-custom-constants
> Add support for kernel32.GetThreadLocale

- speakeasy/winenv/api/usermode/user32.py
This is adding in support for string functions in User32.dll
According to MSDN the strings get updated in place and the length of the replacement is returned. 
Ref: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-charlowerbuffa
> Update user32.py 

- speakeasy/config_schema.json
- speakeasy/configs/default.json
- speakeasy/configs/win10_basic_analysis.json
- speakeasy/configs/win10_full_analysis.json
- speakeasy/configs/win7_full_analysis.json
- speakeasy/windows/hammer.py
- speakeasy/windows/winemu.py
- speakeasy/winenv/api/usermode/gdi32.py
- speakeasy/winenv/api/usermode/kernel32.py
- speakeasy/winenv/api/usermode/lz32.py
- speakeasy/winenv/api/usermode/msi32.py
- speakeasy/winenv/api/usermode/msimg32.py
- speakeasy/winenv/api/usermode/user32.py
- speakeasy/winenv/api/winapi.py
- speakeasy/winenv/defs/windows/windef.py
First stab at API hammering mitigation. Count the number of times a given API is called (paired with its return address). If above the given threshold, assume this is useless anti-sandbox AP hammering & attempt to patch the emulated bytes to prevent the API call and requiring Speakeasy to deal with it. Very incomplete, and currently based on a few examples seen some mass malware for 32-bit x86. 
Two types of calls are supported: call dword ptr [import_addr] and call <reg> are attempted to be dealt with. The first is easy, as there are enough bytes to patch in stack fixup code. The second changes the <reg> contents to point to allocated space with stack cleanup code, under the assumption (not always correct) that if we're in a tight loop with the register initialized prior to the loop with …
> Initial API hammering mitigation

- speakeasy/config_schema.json
- speakeasy/windows/hammer.py
We want some API functions to be allowed despite triggering API hammering detection logic. Placeholder and start of list, with optional for list to be pulled from config.
> Adding API hammering allow_list

- speakeasy/windows/winemu.py
Provides return address when an unsupported API is called. Example: `Unsupported API: shlwapi.wnsprintfA (ret: 0x140009915)`
Further addresses #54.
> Add retn addr to unsupported API message

- speakeasy/winenv/api/kernelmode/ntoskrnl.py
The order of the fields was inverted, the return value was incorrect and the `ReturnLength` was not set correctly.
Would it be possible to label this repository as `hacktoberfest` or label this PR as `hacktoberfest-accepted`? See [here](https://hacktoberfest.digitalocean.com/hacktoberfest-update) for details.
> Fix SYSTEM_INFORMATINO_CLASS.SystemKernelDebuggerInformation

- speakeasy/winenv/api/usermode/msvcrt.py
Update MSVCRT to support `calloc`
Documentation is for the call is https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/calloc?view=msvc-160
To be as accurate as possible, I initialized the memory with `0x00` per calloc's documentation.
> Update msvcrt.py with calloc

- speakeasy/winenv/api/usermode/kernel32.py
Encountered an issue with a 64-bit `cchWideChar` value when emulating MD5 `df00d1192451268c31c1f8568d1ff472`.
> MultiByteToWideChar update

- speakeasy/winenv/api/usermode/kernel32.py
`GetLongPathName` implementation is essentially a placeholder. It mirrors the short path it receives.
> Added GetLongPathName and CreateMutexEx support

- speakeasy/config_schema.json
- speakeasy/configs/default.json
- speakeasy/configs/win10_basic_analysis.json
- speakeasy/configs/win10_full_analysis.json
- speakeasy/configs/win7_full_analysis.json
- speakeasy/windows/winemu.py
This is a new option called "functions_always_exist", similar to "modules_always_exist", but for function.
It pretends that every function exists that the target sample tries to call, and returns a fake value. This is great for quick debugging, or when trying to determine all the missing API hooks. 
Currently this always returns a fixed constant 1 (one) as the return value from the faked function.
> Added a new "functions always exist" mode

- speakeasy/winenv/api/usermode/kernel32.py
The lstrcpyA API hook currently doesn't add the terminating NULL character after the destination string, resulting in junk data after the strings. This MR amend this problem.
> Fixed missing NULL byte in the lstrcpyA API hook

- .gitignore
- speakeasy/binemu.py
- speakeasy/configs/default.json
Added modules to default configuration. Use case is MD5 `df00d1192451268c31c1f8568d1ff472`.
Additional misc. updates:
* Added `.gitignore` entry for PyCharm
* Added registers to x64 `get_register_state`
> Default configuration update

- speakeasy/windows/winemu.py
Currently the APIs in the export table are ordered alphabetically from all of the hooks specified. The code then appends an 'A' and 'W' variant of each hooked export. The problem is the alphabetic order is not preserved.
For example for user32.dll if you look at the export table you will see:
```
.
.
.
LookupIconIdFromDirectory
MessageBox
MessageBoxEx
MsgWaitForMultipleObjects
.
.
.
LookupIconIdFromDirectoryA
LookupIconIdFromDirectoryA
MessageBoxA
MessageBoxW
MessageBoxExA
MessageBoxExW
MsgWaitForMultipleObjectsA
MsgWaitForMultipleObjectsW
.
.
.
```
As you can see the names are not in order in several ways. This pull request performs a sort of the function names after the addition of the 'A' and 'W' is made.
This came up when looking at malware which was manually parsing the export table …
> Export table API Ordering

- speakeasy/winenv/api/kernelmode/ntoskrnl.py
The ViewSize pointer was not used as an OUT to indicate the size of the created view.
> Fixed ViewSize population in ZwMapViewOfSection

- MANIFEST.in
This fixes #122 so that the library can be properly installed on Windows by running `python setup.py install`.
> Fix recursive paths in MANIFEST.in for installing with setup.py

- setup.py
Quick change to make sure that the unicorn version requirement in `setup.py` is updated from `1.0.2rc4` to `1.0.2`.
Related to this issue: https://github.com/fireeye/speakeasy/issues/130
This pull request should also fix this issue on Remnux: https://github.com/REMnux/salt-states/issues/172
> Updated required unicorn version in setup.py

- speakeasy/binemu.py
- speakeasy/speakeasy.py
- speakeasy/windows/winemu.py
In #128 I asked if it was possible to have multiple hook for the same API. If you considered this request fair, I made a simple implementation.
Since I don't know how I should provide you the tests, this little snippet demonstrate the functionality added.
```python3
from speakeasy import Speakeasy
def call_actions(emu, api_name, func, params):
rv = func(params)
print("called second")
emu.counter += 1
return rv
def call_actions2(emu, api_name, func, params):
rv = func(params)
print("called_first")
emu.counter = 1
return rv
se = Speakeasy()
api = "GetSystemTimeAsFileTime"
module = se.load_module("tests/bins/antidbg.exe")
se.add_api_hook(call_actions, module="*", api_name=api)
se.add_api_hook(call_actions2, module="kernel32", api_name=api)
se.run_module(module)
assert(se.emu.counter == 2) …
```
> Added multi_hook for the same API call

- speakeasy/winenv/api/usermode/advapi32.py
- speakeasy/winenv/api/usermode/wininet.py
Hey there!
I found out that there were not logs in the registry report if the sample tries to create a new key or tries to enumerate the registries subkeys.
I have no idea if these logs were missing because were considered not important, if this was the case, feel free to close the pr.
> Adding list_subkeys and create_key log 

- speakeasy/profiler.py
In many cases, like if a file is copied, `log_file_access` is called without size, which makes it crash:
```
0x100014cc: Error while calling API handler for KERNEL32.CopyFileW:
Traceback (most recent call last):
File "speakeasy/speakeasy/windows/winemu.py", line 1126, in handle_import_func
rv = self.api.call_api_func(mod, func, argv, ctx=default_ctx)
File "speakeasy/speakeasy/winenv/api/winapi.py", line 77, in call_api_func
return func(mod, self.emu, argv, ctx)
File "speakeasy/speakeasy/winenv/api/usermode/kernel32.py", line 3258, in CopyFile
self.log_file_access(_dst, 'write')
File "speakeasy/speakeasy/winenv/api/api.py", line 215, in log_file_access
profiler.log_file_access(run, path, event_type, data, handle,
File "speakeasy/speakeasy/profiler.py", line 200, in log_file_access …
```
> Bug fix in log_file_access

- speakeasy/windows/winemu.py
Check for API hammering when function handler is missing but a user hook is present
> Additional API hammering check

- speakeasy/winenv/api/usermode/kernel32.py
The real CreateFile API only reads a DWORD of the disposition value. Therefore it is completely valid for malicious programs/shellcode to pass a QWORD (in x64) with invalid leading bytes and have the system API work (e.g. 0xcccccccc00000003 = OPEN_EXISTING). Without this change, Speakeasy fails to return a handle because it can't match the disposition parameter with any of the windef disposition values.
> Fix CreateFile emulation

- requirements.txt
- speakeasy/binemu.py
- speakeasy/windows/winemu.py
- speakeasy/winenv/api/usermode/advapi32.py
- speakeasy/winenv/api/usermode/user32.py
- speakeasy/winenv/defs/windows/advapi32.py
- speakeasy/binemu.py: `read_mem_string`: encoding changed to latin1
instead of utf-8
- speakeasy/windows/winemu.py: `map_pe`: use `pe.image_size` instead of
`len(pe.mapped_image)`, which correctly reflects the size of the virtual
address space of the emulated process
- speakeasy/windows/winemu.py: `_dispatch_seh_x86`: unconditionally
clobber `ebx`, because the Windows kernel clobbers it
- speakeasy/windows/winemu.py: `_continue_seh_x86`: unconditionally
restore thread context so registers continue to reflect what they were before the
exception happened
I also added API hooks for `CryptDecrypt`, `CryptDeriveKey`, and
`SetWindowLong` (which is just a stub). `CryptDecrypt` and `CryptDeriveKey`
only support RC4. With the inclusion of RC4 stuff, `pycryptodome` is now
a dependency.
> Bug fixes, CryptDecrypt, CryptDeriveKey, SetWindowLong

- speakeasy/windows/win32.py
This addition of adding the ".exe" extension causes improper emulated API results when the emulated program attempts to parse its command line options. The function https://github.com/fireeye/speakeasy/blob/bf876c72c362e31193b9d3493d31a78ecbf674ef/speakeasy/windows/win32.py#L125
data parameter is optional, and so many of the examples (including run_speakeasy.py) do not set/use it when calling `load_module` This means the '.exe' will be appended to the file_name and that if an emulated process, accesses argv[0] the output will be: `C:\Windows\System32\Malware.exe.exe` (default config file) When argv[0] should return `C:\Windows\System32\Malware.exe`
> Fix bug in emulated argument parsing

- speakeasy/binemu.py
- speakeasy/common.py
- speakeasy/engines/unicorn_eng.py
- speakeasy/speakeasy.py
- speakeasy/windows/fileman.py
- speakeasy/windows/objman.py
- speakeasy/windows/winemu.py
- speakeasy/winenv/api/usermode/kernel32.py
- speakeasy/winenv/api/usermode/rpcrt4.py
- speakeasy/winenv/api/usermode/shell32.py
- speakeasy/speakeasy.py: expose set_dyn_code_hook as a public API
- speakeasy/windows/fileman.py: `FileManager` constructor/`get_file_from_path`: changes to permit serving the actual file on disk that corresponds to the current emulated sample. This allows samples, for example, to correctly query its own file size
- speakeasy/windows/fileman.py: `get_emu_file`: if there are any decoy DLLs present, and the emulated sample asks for a memory mapping of them, Speakeasy used to just serve the default file, now it serves the correct decoy
- Added support for implicit TLS
- speakeasy/windows/objman.py: `Thread` class: `init_tls`
- speakeasy/windows/winemu.py: `WindowsEmulator` class: `init_tls` (same name, calls into `Thread` `init_tls`)
- speakeasy/winenv/api/usermode/kernel32.py
- Implement …
> Bug fixes, implicit TLS support

- speakeasy/winenv/api/usermode/dnsapi.py
Fix a logic bug in dnsapi.DnsQuery_A where the `rr` variable was not set sometimes.
Before, I had this error: 
This PR fixes this.
> Fix a logic bug in dnsapi.DnsQuery_A

- speakeasy/winenv/api/usermode/ntdll.py
During some normal usage I realized that the ntdll.LdrLoadDll is calling `normalize_dll_name` object referring to `self`.
But we actually do not have this object here.
The error dropped is 
```
Error while calling API handler for ntdll.LdrLoadDll
Caught error: 'Ntdll' object has no attribute 'normalize_dll_name'
```
I fixed it by applying the same calling convention seen in `/winenv/api/usermode/kernel32.py`, so adding the call through `winemu`.
From my tests it works.
> Fix for Error while calling API handler for ntdll.LdrLoadDll:

- setup.py
- speakeasy/__main__.py
- speakeasy/cli.py
This pull request moves `run_speakeasy.py` into `speakeasy/cli.py`, and creates an `entrypoint` field in `setup.py` which installs a script named `speakeasy` when installing the python module. The result is that a user can do:
```sh
$ pip install speakeasy-emulator
$ python setup.py install
$ speakeasy --help
```
I also added a `__main__.py` file to the module which simply executes the CLI entrypoint. This makes the following also valid/possible:
```sh
python -m speakeasy
```
This would fix #69.
I'm just realizing that `python-black` formatted the files which I edited. It appears the only changes made were using double quotes instead of single. If this is unacceptable for the purposes of this pull request, I'm happy to revert the changes, and then ensure that it's not formatted with Black …
> Added entrypoint script under speakeasy.cli

- speakeasy/winenv/api/usermode/shlwapi.py
Small API addition.  
Adding in support for `StrStr`, Borrowing the logic from `StrStrI` within Shlwapi.  
Encountered `StrStrW` within sample, can be observed in `be514549a2e654706aeeaa15c8cffce504f0e271c904fe07d865f3999ebaa61f`
> Support for StrStr in shlwapi

- Dockerfile
was failing on docker image curation due to a missing requirements.txt file, which is now being pulled in.
was previously failing to build
> fix missing requirements.txt in dockerfile

- speakeasy/windows/win32.py
Hi guys! I was executing some shellcodes through speakeasy and I encountered the following error
```
0x77001b12: shellcode: Caught error: 'Win32Emulator' object has no attribute 'bin_base_name'
* Finished emulating
```
The patch that I made is very small and cover only this small use case, but the IDE is warning me that can be more attribute that are uninitialized in the `win32.py` module.
> Fix shellcode bin_base_name uninitialized

- speakeasy/winenv/api/usermode/msvcrt.py
Quick fix to the API to avoid the write if destination of converted pointer is null
> Fix in msvcrt!mbstowcs_s to avoid to write null pReturnValue

- speakeasy/winenv/api/usermode/ntdll.py
They're very similar to FindResourceA and LoadResource from kernel32, so I tried to reuse some of the functionality from kernel32.py that was built for handling those. 
1a57412ab2edd77103fd75768ba146dd is a good test case. It's a crypter used to wrap Trickbot and uses these APIs to find and load the resource containing the RC4 encrypted payload.
> Added LdrFindResource_U and LdrAccessResource

- speakeasy/winenv/api/usermode/kernel32.py
[mandiant/speakeasy] undefined name 'out' (Issue #197)
> Fix of Issue #197

- speakeasy/winenv/api/usermode/ws2_32.py
- speakeasy/winenv/defs/winsock/ws2_32.py
Fixed a bug that didn't account for `hostent.h_addr_list` being NULL-terminated.
> ws2_32.gethostbyname fix

- speakeasy/binemu.py
- speakeasy/config_schema.json
- speakeasy/configs/default.json
- speakeasy/winenv/api/usermode/iphlpapi.py
- speakeasy/winenv/defs/windows/iphlpapi.py
Primary intent was to support network adapters based on the `GetAdaptersInfo` function. Includes the ability to specify a list of network adapters in the configuration. For each adapter in the config, a minimal list of properties can be defined (e.g., name, description, type, IP address, MAC address).
> Initial iphlpapi.dll support

- speakeasy/windows/common.py
- speakeasy/winenv/api/usermode/kernel32.py
* Fixed `FindResource`, `LoadResource`, `LockResource`, and `SizeofResource` implementations
* Prior implementation did not return expected resource structures as they should exist in memory.
* Added `FreeResource` API
* Moved resource-related APIs next to each other in `kernel32.py` 
Binaries used to test updates include [this PMA sample](https://www.virustotal.com/gui/file/ae8a1c7eb64c42ea2a04f97523ebf0844c27029eb040d910048b680f884b9dce).
> kernel32 resource API updates

- speakeasy/windows/fileman.py
- speakeasy/winenv/api/usermode/kernel32.py
Currently the `MapViewOfFile`  maps the loaded file as a contiguous stream of bytes.
But this is not always the case: when a file is mapped and SEC_IMAGE protection flag has been set in the previous `CreateFileMapping`, the file is mapped as a PE file, with all the sections mapped accordingly. If this is not supported, following calls on the mapped memory can bring to unexpected results (this is often used by unhook functions).
I added:
- a `get_prot` method in the `FileMap` class to get the current protection
- support of mapping in `MapViewOfFile`
> Modification to "MapViewOfFile" 

- speakeasy/speakeasy.py
- speakeasy/windows/win32.py
Provide parameter for adjusting the stack commit size when emulating shellcode payloads that require a stack size larger that 16384 bytes.
> Adding stack_commit parameter for shellcode

- speakeasy/winenv/api/usermode/kernel32.py
Returns the locale identifier for the system default locale, identified by [LOCALE_SYSTEM_DEFAULT](https://learn.microsoft.com/en-us/windows/desktop/Intl/locale-system-default).
> Added GetSystemDefaultLCID

- speakeasy/winenv/api/kernelmode/ntoskrnl.py
- speakeasy/winenv/api/usermode/advapi32.py
- speakeasy/winenv/api/usermode/user32.py
- speakeasy/winenv/defs/nt/ddk.py
Modified ZwMapViewOfSection in order to use win_perms_to_emu_perms to successfully map Windows permission to emulation engine permissions. Definition of win_perms_to_emu_perms is also added
> Fix potential ZwMapViewOfSection and GetKeyboardLayoutList bugs and add support for SystemCodeInformation class

- speakeasy/winenv/api/usermode/shell32.py
- speakeasy/winenv/defs/windows/shell32.py
I made this implementation of ShellExecuteEx (should work for both A and W variant):
- I implemented the structure in `speakeasy/winenv/defs/windows/shell32.py`
- the call to `ShellExecuteEx` parse the parameters and then call the existing `ShellExecute`. 
I did in this way to avoid to duplicate code, even I'm not sure if this the correct way. What do you think?
Feel free to reject it anyway ;-)
> Implementation of ShellExecuteEx

- speakeasy/windows/winemu.py
KUSER_SHARED_DATA has a read-only memory mapping at the fixed address 0x7ffe0000, which is sometimes accessed directly by malware.
Ideally this should be a read-only copy of the actual KUSER_SHARED_DATA structure (that is already mapped a few lines above), but since we are not actually filling this structure with credible values, just having this mapped in memory will work for now, and will get rid of some invalid memory read errors to fix emulation of certain malware binaries.
References:
- https://labs.jumpsec.com/abusing-shareduserdata-for-defense-evasion-and-exploitation-2/
- https://medium.com/@boutnaru/the-windows-concept-journey-shareduserdata-kuser-shared-data-78e980d628e3
> Added missing read-only KUSER_SHARED_DATA mapping
