.github/workflows/test.yml
see some example runs here: https://github.com/williballenthin/speakeasy/actions
=> configure CI testing via github actions

speakeasy/winenv/api/usermode/kernel32.py
Function has no return value, so this is just a stub for formatting the output of these calls.
=> Add support for kernel32.OutputDebugStringA/W

speakeasy/winenv/api/usermode/msvcrt.py
Add msvcrt.clock following example of kernel32.py tick_counter
=> add msvcrt.clock

speakeasy/winenv/api/usermode/advapi32.py
add advapi32.RegisterServiceCtrlHandler
add advapi32.SetServiceStatus
=> Add a couple advapi32 service APIs

speakeasy/winenv/api/usermode/msvcrt.py
Adding in support for toupper as described in: 
https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/toupper-toupper-towupper-toupper-l-towupper-l?view=vs-2019
=> Support for msvcrt.toupper

speakeasy/winenv/api/usermode/msvcrt.py
More support for msvcrt math functions
=> Adding msvcrt.sin and msvcrt.abs

speakeasy/winenv/api/usermode/advapi32.py
If user is admin per config, assume process is elevated and set TokenElevation to true for GetTokenInformation.
=> Change advapi32.GetTokenInformation to set TokenElevation if admin

speakeasy/windows/common.py, speakeasy/windows/win32.py, speakeasy/windows/winemu.py, speakeasy/winenv/api/kernelmode/ntoskrnl.py, speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/ntdll.py
Support for some packers that use both TLS and unhandled exception filters to redirect control flow.
=> Support for unhandled exception filters, further API adds

run_speakeasy.py
Run emulation within the current process to enable breakpoint use.
=> Adding --no-mp flag to run_speakeasy.py

speakeasy/binemu.py, speakeasy/windows/win32.py, speakeasy/winenv/api/api.py
When wild cards are not used, API hooks will be stored in a simple dict. This provides a significant speed boost when wild cards aren't needed.
=> API hook speed improvements

speakeasy/winenv/api/usermode/msvcrt.py
Same implementation as strstr, just adjusting for wide.
=> Update msvcrt.py with wcsstr

speakeasy/config_schema.json, speakeasy/winenv/api/usermode/msvcrt.py, speakeasy/winenv/api/usermode/shlwapi.py
adds max_instructions to schema
=> Config schema update

speakeasy/winenv/api/usermode/msvcrt.py
This implementation is the same as __getmainargs.
=> Update msvcrt.py adding support for __wgetmainargs

speakeasy/winenv/api/usermode/ole32.py, speakeasy/winenv/defs/windows/com.py
Added support for COM initialization functions.
=> COM updates

speakeasy/windows/winemu.py, speakeasy/winenv/api/kernelmode/ntoskrnl.py
Implemented the happy path without actually registering any callbacks for now. Also improved error messaging to make it easier to debug and fixed some minor bugs.
Would be nice if you could add the `hacktoberfest-accepted` label again 🙂
=> Add various APIs in ntoskrnl + minor fixes

run_speakeasy.py
> When in raw mode, offset (in hex) to start emulating
=> run_speakeasy: add cli arg for raw_offset

speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/winhttp.py
Hi, 
Here is an implementation for kernel32.QueryPerformanceFrequency and winhttp.WinHttpCrackUrl (that I copied mostly from InternetCrackUrl)
=> Add two new functions

speakeasy/windows/cryptman.py, speakeasy/winenv/api/usermode/advapi32.py, speakeasy/winenv/api/usermode/ncrypt.py, speakeasy/winenv/api/usermode/shlwapi.py, speakeasy/winenv/api/winapi.py
Includes a basic implementation for crypto keys in `cryptman.py`.
=> Added ncrypt.dll APIs and wnsprintfA

speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/shlwapi.py, speakeasy/winenv/defs/windows/kernel32.py
Also includes minor update to `wnsprintfA`.
=> Improved GetLocaleInfo

speakeasy/winenv/api/kernelmode/__init__.py, speakeasy/winenv/api/usermode/__init__.py, speakeasy/winenv/api/winapi.py
This pull request adds a new feature that automatically collects and loads API handler classes.
=> Automatically collect and load API handlers

speakeasy/winenv/api/usermode/ws2_32.py, speakeasy/winenv/defs/winsock/winsock.py, speakeasy/winenv/defs/winsock/ws2_32.py
* Expanded `setsockopt`
* APIs added:
* `getaddrinfo`
* `freeaddrinfo`
* `getsockopt`
=> ws2_32 updates

speakeasy/winenv/api/usermode/advapi32.py, speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/mpr.py, speakeasy/winenv/api/usermode/ntdll.py, speakeasy/winenv/api/usermode/ole32.py, speakeasy/winenv/defs/windows/advapi32.py, speakeasy/winenv/defs/windows/com.py, speakeasy/winenv/defs/windows/mpr.py
* Numerous API placeholders added to allow execution to continue.
* COM fix; added `IWbemContext` interface
=> Usermode API updates

speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/user32.py, speakeasy/winenv/defs/windows/kernel32.py
* `Sleep` fix
* Changed `GetSystemDirectory` and `GetWindowsDirectory` behavior
* `GetFileAttributesEx` update
* Added `user32.GetKeyboardLayoutList` API
=> kernel32 and user32 updates

speakeasy/binemu.py, speakeasy/common.py, speakeasy/engines/unicorn_eng.py, speakeasy/speakeasy.py
Added two new API functions for adding instruction hooks:
* add_SYSCALL_instruction_hook(syscall_hook)
* add_IN_instruction_hook(in_hook)
=> Added support for IN and SYSENTER instruction hooks

speakeasy/winenv/api/usermode/kernel32.py
SetHandleInformation
GetHandleInformation
They just return success for the time being
=> Added support for Windows API:

speakeasy/profiler.py
When the same file was being accessed multiple time, the data that was being read/wrote was not updated
=> Fix multiple file read/write

speakeasy/winenv/api/usermode/advapi32.py, speakeasy/winenv/api/usermode/kernel32.py
bug fix for wide character writing
new API handler for advapi32.OpenService
=> minor improvements

speakeasy/binemu.py, speakeasy/windows/win32.py
- add helpers for read/write pointer sized values in memory
- closes #161: emulate ServiceMain by passing default args to the routine
=> emulate ServiceMain

speakeasy/windows/winemu.py
=> winemu: log when an emulation begins

speakeasy/winenv/api/usermode/kernel32.py
Added support for two Kernel32 API:
SetThreadLocale
IsValidLocale
=> Kernel32 API: SetThreadLocale, IsValidLocale

speakeasy/winenv/api/usermode/msvcrt.py
used info from here: https://github.com/MiroKaku/ucxxrt/blob/master/src/i386/ehprolog.asm#L36-L45
closes #167
=> msvcrt: add _EH_prolog

speakeasy/winenv/api/usermode/ws2_32.py
Add a very basic support for the ws2_32.WSAIoctl function.
Before, had this error:
Now it works!
=> Add a very basic support for the ws2_32.WSAIoctl function.

speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/msvcrt.py, speakeasy/winenv/defs/windows/kernel32.py
Minor API updates/additions for: 
msvcrt._stricmp
msvcrt._wcsicmp
msvcrt.wcscmp
kernel32.DuplicateHandle
kernel32.GetThreadPriority
kernel32.UnhandledExceptionFilter
kernel32.SetUnhandledExceptionFilter
=> Minor API additions

speakeasy/winenv/api/usermode/msvcrt.py
I implemented these API for correct emulation of some C++ compiled EXE
`__p_acmdln`: calls the existing `_acmdln`
`_onexit`: just returns the func (as the other onexit funcs)
`mbstowcs_s`: brand new implementation, quite different from the one in `ntoskrnl.py`
`_wcsnicmp`: this one comes from the implementation in `ntoskrnl.py`
=> 4 new API for C++ runtime

speakeasy/winenv/api/usermode/kernel32.py
Used by some crypted qakbot I was looking at: d4b6a981216ed1aa8f62a2b2249e3674. Nearly an exact copy of the already existing implementation for HeapSize
=> Added GlobalSize implementation

speakeasy/winenv/api/usermode/gdi32.py, speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/oleaut32.py, speakeasy/winenv/api/usermode/user32.py, speakeasy/winenv/api/usermode/wininet.py, speakeasy/winenv/defs/wininet.py
* Added API function placeholders for `CreateDIBSection` and `GetClientRect`
* Added API function `SysAllocStringLen`
* `MultiByteToWideChar`: fixed return value for a specific case
* `GetProcAddress`: fixed potential "variable referenced before assignment"
* Minor `wininet` updates
=> Minor API updates

speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/user32.py
- KERNEL32.AllocConsole
- USER32.GetAsyncKeyState
=> Added two simple APIs

speakeasy/winenv/api/usermode/kernel32.py
Is just a  simplified version for SetFilePointerEx.
=> Added SetFilePointerEx. Is just SetFilePointer adapted for Win Api.

speakeasy/winenv/api/usermode/advapi32.py
Added StartServiceA and ControlService dummy functions
=> Added StartServiceA and ControlService dummy functions

speakeasy/binemu.py, speakeasy/winenv/api/kernelmode/ntoskrnl.py, speakeasy/winenv/api/usermode/crypt32.py, speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/msvcrt.py, speakeasy/winenv/api/usermode/shell32.py
Hi team, 
this PR implements a couple of additions and fixes for speakeasy we would like to contribute to upstream. Thanks for your great work with the emulator!
=> changes + additions

speakeasy/winenv/api/usermode/kernel32.py
=> Added dummy functions for

speakeasy/windows/win32.py
=> Allocate SizeOfStackReserve instead of fixed value in 'load_module'

speakeasy/winenv/api/usermode/kernel32.py, speakeasy/winenv/api/usermode/msvcrt.py
CreateSemaphoreW()
SetThreadStackGuarantee()
SetThreadDescription()
InitOnceBeginInitialize()
_errno()
fputc()
signal()
=> Add several API hooks to emulate through couple of Rust samples.

README.md, speakeasy/cli.py
=> Typo: Fixed missing whitespace
